<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.1</Version>
    <Product>SMTC Reader</Product>
    <Authors>BarryZed</Authors>
    <Company>BarryZed</Company>
    <Copyright>Copyright (c) 2026 BarryZed</Copyright>
    <RepositoryUrl>https://github.com/Barrryy/SMTC-reader</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
