#Requires -Version 5.1
<#
.SYNOPSIS
    Renders docs/sample-console.txt into docs/screenshot.png.

.DESCRIPTION
    The README image is generated rather than captured, so it can be regenerated by
    anyone and stays in sync with the tool. The text comes straight from
    docs/sample-console.txt, which SampleConsoleTests asserts against the real console
    renderer - so this script colours the output, it never invents it.

    Windows only, because it uses System.Drawing.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\make-screenshot.ps1
#>
[CmdletBinding()]
param(
    [string]$Text,
    [string]$Output,
    [int]$FontSize = 13,
    [int]$LineHeight = 20
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
if (-not $Text) { $Text = Join-Path $root 'docs\sample-console.txt' }
if (-not $Output) { $Output = Join-Path $root 'docs\screenshot.png' }

if (-not (Test-Path -LiteralPath $Text)) { throw "missing input: $Text" }

# --- palette (a dark terminal theme) ---
$background = [System.Drawing.Color]::FromArgb(12, 12, 12)
$border = [System.Drawing.Color]::FromArgb(43, 43, 43)
$foreground = [System.Drawing.Color]::FromArgb(204, 204, 204)
$dim = [System.Drawing.Color]::FromArgb(96, 96, 96)
$rule = [System.Drawing.Color]::FromArgb(74, 74, 74)
$label = [System.Drawing.Color]::FromArgb(156, 220, 254)
$section = [System.Drawing.Color]::FromArgb(79, 193, 255)
$heading = [System.Drawing.Color]::FromArgb(255, 255, 255)
$accent = [System.Drawing.Color]::FromArgb(220, 220, 170)
$yes = [System.Drawing.Color]::FromArgb(78, 201, 176)
$no = [System.Drawing.Color]::FromArgb(241, 76, 76)

$lines = @(Get-Content -LiteralPath $Text -Encoding UTF8)
$fontFamily = 'Consolas'
$font = New-Object System.Drawing.Font($fontFamily, $FontSize, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$boldFont = New-Object System.Drawing.Font($fontFamily, $FontSize, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$brushes = @{}
foreach ($pair in @(
        @('background', $background), @('border', $border), @('foreground', $foreground),
        @('dim', $dim), @('rule', $rule), @('label', $label), @('section', $section),
        @('heading', $heading), @('accent', $accent), @('yes', $yes), @('no', $no))) {
    $brushes[$pair[0]] = New-Object System.Drawing.SolidBrush($pair[1])
}

# Measure a monospace character so segments can be placed by column index.
$probe = New-Object System.Drawing.Bitmap 1, 1
$probeGraphics = [System.Drawing.Graphics]::FromImage($probe)
$charWidth = $probeGraphics.MeasureString('0123456789', $font).Width / 10.0
$probeGraphics.Dispose()
$probe.Dispose()

$padX = 18
$padY = 16
$widest = ($lines | ForEach-Object { $_.Length } | Measure-Object -Maximum).Maximum
if (-not $widest) { $widest = 40 }
$width = [int][Math]::Ceiling($widest * $charWidth) + ($padX * 2)
$height = ($lines.Count * $LineHeight) + ($padY * 2)

$bitmap = New-Object System.Drawing.Bitmap($width, $height)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::ClearTypeGridFit
$graphics.FillRectangle($brushes['background'], 0, 0, $width, $height)
$graphics.DrawRectangle((New-Object System.Drawing.Pen($border, 1)), 0, 0, $width - 1, $height - 1)

function Write-Segments {
    param(
        [System.Drawing.Graphics]$Graphics,
        [array]$Segments,
        [double]$StartColumn,
        [double]$Y,
        [System.Drawing.Font]$Font
    )

    $x = $padX + ($StartColumn * $charWidth)
    foreach ($segment in $Segments) {
        if ($segment.Text.Length -eq 0) { continue }
        $Graphics.DrawString($segment.Text, $Font, $brushes[$segment.Brush], [single]$x, [single]$Y)
        $x += $segment.Text.Length * $charWidth
    }
}

$y = $padY
foreach ($line in $lines) {
    $segments = @()
    $fontToUse = $font

    if ($line.StartsWith('===')) {
        $segments = @(@{ Text = $line; Brush = 'rule' })
    }
    elseif ($line.StartsWith('-- ')) {
        $segments = @(@{ Text = $line; Brush = 'section' })
    }
    elseif ($line.StartsWith('Tip:')) {
        $segments = @(@{ Text = $line; Brush = 'dim' })
    }
    elseif ($line.StartsWith(' [')) {
        $fontToUse = $boldFont
        $split = $line.IndexOf('  <-- ', [StringComparison]::Ordinal)
        if ($split -ge 0) {
            $segments = @(
                @{ Text = $line.Substring(0, $split); Brush = 'heading' },
                @{ Text = $line.Substring($split); Brush = 'accent' })
        }
        else {
            $segments = @(@{ Text = $line; Brush = 'heading' })
        }
    }
    elseif ($line.Contains(' : ')) {
        $split = $line.IndexOf(' : ', [StringComparison]::Ordinal) + 1
        $value = $line.Substring($split + 2)
        $valueBrush = 'foreground'
        if ($value -eq '✓') { $valueBrush = 'yes' }
        elseif ($value -eq '✗') { $valueBrush = 'no' }
        $segments = @(
            @{ Text = $line.Substring(0, $split); Brush = 'label' },
            @{ Text = $line.Substring($split); Brush = $valueBrush })
    }
    else {
        $segments = @(@{ Text = $line; Brush = 'foreground' })
    }

    Write-Segments -Graphics $graphics -Segments $segments -StartColumn 0 -Y $y -Font $fontToUse
    $y += $LineHeight
}

$graphics.Dispose()
$bitmap.Save($Output, [System.Drawing.Imaging.ImageFormat]::Png)
$bitmap.Dispose()
$font.Dispose()
$boldFont.Dispose()
foreach ($brush in $brushes.Values) { $brush.Dispose() }

"screenshot: {0}  ({1} x {2}, {3:N1} KB)" -f $Output, $width, $height, ((Get-Item -LiteralPath $Output).Length / 1KB)
